package services

import (
	"errors"
	"fmt"
	"time"

	"gymapp-backend/dto"
	"gymapp-backend/models"
	"gymapp-backend/repositories"
)

var (
	ErrBlockNotFound    = errors.New("schedule block not found")
	ErrNotBlockOwner    = errors.New("not block owner")
)

type ScheduleService struct {
	scheduleRepo    *repositories.ScheduleRepo
	appointmentRepo *repositories.AppointmentRepo
	settingsRepo    *repositories.SettingsRepo
	activitySvc     *ActivityService
}

func NewScheduleService(
	scheduleRepo *repositories.ScheduleRepo,
	appointmentRepo *repositories.AppointmentRepo,
	settingsRepo *repositories.SettingsRepo,
	activitySvc *ActivityService,
) *ScheduleService {
	return &ScheduleService{
		scheduleRepo:    scheduleRepo,
		appointmentRepo: appointmentRepo,
		settingsRepo:    settingsRepo,
		activitySvc:     activitySvc,
	}
}

func (s *ScheduleService) GetAvailability(proID, locationID, dateStr string) (*dto.AvailabilityResponse, error) {
	date, err := time.Parse("2006-01-02", dateStr)
	if err != nil {
		return nil, fmt.Errorf("invalid date format, use YYYY-MM-DD")
	}

	dayOfWeek := int(date.Weekday())

	// 1. Get working hours for this day
	hours, err := s.scheduleRepo.FindWorkingHours(proID, locationID, dayOfWeek, date)
	if err != nil {
		return nil, err
	}

	// Day boundaries
	dayStart := time.Date(date.Year(), date.Month(), date.Day(), 0, 0, 0, 0, time.UTC)
	dayEnd := dayStart.Add(24 * time.Hour)

	// 2. Get blocks for this day
	blocks, _ := s.scheduleRepo.FindBlocksByDateRange(proID, dayStart, dayEnd)

	// 3. Get existing appointments for this day
	appointments, _ := s.appointmentRepo.FindByProfessionalAndDateRange(proID, dayStart, dayEnd)

	// 4. Get slot settings
	slotDuration := 60
	slotGap := 0
	settings, err := s.settingsRepo.FindByUserID(proID)
	if err == nil {
		slotDuration = settings.SlotDurationMinutes
		slotGap = settings.SlotGapMinutes
	}

	// 5. Generate slots
	var slots []dto.TimeSlot
	slotMap := make(map[string]int) // maps start_time -> index in slots slice

	for _, wh := range hours {
		whStart, _ := time.Parse("15:04:05", wh.StartTime)
		whEnd, _ := time.Parse("15:04:05", wh.EndTime)

		cursor := time.Date(date.Year(), date.Month(), date.Day(), whStart.Hour(), whStart.Minute(), 0, 0, time.UTC)
		endBound := time.Date(date.Year(), date.Month(), date.Day(), whEnd.Hour(), whEnd.Minute(), 0, 0, time.UTC)

		for cursor.Add(time.Duration(slotDuration) * time.Minute).Before(endBound) || cursor.Add(time.Duration(slotDuration)*time.Minute).Equal(endBound) {
			slotEnd := cursor.Add(time.Duration(slotDuration) * time.Minute)
			available := true

			// Check blocks
			for _, b := range blocks {
				if cursor.Before(b.EndTime) && slotEnd.After(b.StartTime) {
					available = false
					break
				}
			}

			// Check appointments WITH a client (meaning they are booked)
			if available {
				for _, a := range appointments {
					if a.ClientID != nil && cursor.Before(a.EndTime) && slotEnd.After(a.StartTime) {
						available = false
						break
					}
				}
			}

			startTimeStr := cursor.Format("15:04")
			endTimeStr := slotEnd.Format("15:04")

			slots = append(slots, dto.TimeSlot{
				StartTime: startTimeStr,
				EndTime:   endTimeStr,
				Available: available,
			})
			slotMap[startTimeStr] = len(slots) - 1

			cursor = slotEnd.Add(time.Duration(slotGap) * time.Minute)
		}
	}

	// Add manual open slots (appointments with ClientID == nil)
	for _, a := range appointments {
		if a.ClientID == nil {
			startStr := a.StartTime.Format("15:04")
			endStr := a.EndTime.Format("15:04")

			// If slot already exists in slots (generated by working hours), ensure it is marked available (if not blocked by blocks)
			if idx, exists := slotMap[startStr]; exists {
				isBlocked := false
				for _, b := range blocks {
					if a.StartTime.Before(b.EndTime) && a.EndTime.After(b.StartTime) {
						isBlocked = true
						break
					}
				}
				if !isBlocked {
					slots[idx].Available = true
				}
			} else {
				// It's a custom manual open slot outside working hours. Add it!
				isBlocked := false
				for _, b := range blocks {
					if a.StartTime.Before(b.EndTime) && a.EndTime.After(b.StartTime) {
						isBlocked = true
						break
					}
				}
				if !isBlocked {
					slots = append(slots, dto.TimeSlot{
						StartTime: startStr,
						EndTime:   endStr,
						Available: true,
					})
				}
			}
		}
	}

	if slots == nil {
		slots = []dto.TimeSlot{}
	}

	return &dto.AvailabilityResponse{
		Date:           dateStr,
		ProfessionalID: proID,
		LocationID:     locationID,
		Slots:          slots,
	}, nil
}

func (s *ScheduleService) CreateWorkingHours(proID string, req dto.CreateWorkingHoursRequest, ip, ua string) (*dto.WorkingHoursResponse, error) {
	validFrom := time.Now()
	if req.ValidFrom != "" {
		parsed, err := time.Parse("2006-01-02", req.ValidFrom)
		if err != nil {
			return nil, fmt.Errorf("invalid valid_from date")
		}
		validFrom = parsed
	}

	var validUntil *time.Time
	if req.ValidUntil != "" {
		parsed, err := time.Parse("2006-01-02", req.ValidUntil)
		if err != nil {
			return nil, fmt.Errorf("invalid valid_until date")
		}
		validUntil = &parsed
	}

	wh := &models.WorkingHours{
		ProfessionalID: proID,
		LocationID:     req.LocationID,
		DayOfWeek:      req.DayOfWeek,
		StartTime:      req.StartTime,
		EndTime:        req.EndTime,
		ValidFrom:      validFrom,
		ValidUntil:     validUntil,
	}

	if err := s.scheduleRepo.CreateWorkingHours(wh); err != nil {
		return nil, err
	}

	s.activitySvc.Log(&proID, "schedule.hours_updated", "working_hours", &wh.ID, nil, ip, ua)

	var vuStr *string
	if wh.ValidUntil != nil {
		v := wh.ValidUntil.Format("2006-01-02")
		vuStr = &v
	}

	return &dto.WorkingHoursResponse{
		ID:         wh.ID,
		LocationID: wh.LocationID,
		DayOfWeek:  wh.DayOfWeek,
		StartTime:  wh.StartTime,
		EndTime:    wh.EndTime,
		ValidFrom:  wh.ValidFrom.Format("2006-01-02"),
		ValidUntil: vuStr,
	}, nil
}

func (s *ScheduleService) CreateBlock(proID string, req dto.CreateBlockRequest, ip, ua string) (*dto.BlockResponse, error) {
	startTime, err := time.Parse(time.RFC3339, req.StartTime)
	if err != nil {
		return nil, fmt.Errorf("invalid start_time, use RFC3339 format")
	}
	endTime, err := time.Parse(time.RFC3339, req.EndTime)
	if err != nil {
		return nil, fmt.Errorf("invalid end_time, use RFC3339 format")
	}

	var locID *string
	if req.LocationID != "" {
		locID = &req.LocationID
	}
	var reason *string
	if req.BlockReason != "" {
		reason = &req.BlockReason
	}

	block := &models.ScheduleBlock{
		ProfessionalID: proID,
		LocationID:     locID,
		StartTime:      startTime,
		EndTime:        endTime,
		BlockReason:    reason,
	}

	if err := s.scheduleRepo.CreateBlock(block); err != nil {
		return nil, err
	}

	s.activitySvc.Log(&proID, "schedule.block_created", "schedule_block", &block.ID, nil, ip, ua)

	return &dto.BlockResponse{
		ID:          block.ID,
		LocationID:  block.LocationID,
		StartTime:   block.StartTime.Format(time.RFC3339),
		EndTime:     block.EndTime.Format(time.RFC3339),
		BlockReason: block.BlockReason,
	}, nil
}

func (s *ScheduleService) DeleteBlock(proID, blockID, ip, ua string) error {
	block, err := s.scheduleRepo.FindBlockByID(blockID)
	if err != nil {
		return ErrBlockNotFound
	}
	if block.ProfessionalID != proID {
		return ErrNotBlockOwner
	}
	s.activitySvc.Log(&proID, "schedule.block_deleted", "schedule_block", &blockID, nil, ip, ua)
	return s.scheduleRepo.DeleteBlock(blockID)
}

func (s *ScheduleService) GetWorkingHours(proID string) ([]dto.WorkingHoursResponse, error) {
	hours, err := s.scheduleRepo.FindAllWorkingHours(proID)
	if err != nil {
		return nil, err
	}

	var resp []dto.WorkingHoursResponse
	for _, wh := range hours {
		var vuStr *string
		if wh.ValidUntil != nil {
			v := wh.ValidUntil.Format("2006-01-02")
			vuStr = &v
		}
		resp = append(resp, dto.WorkingHoursResponse{
			ID:         wh.ID,
			LocationID: wh.LocationID,
			DayOfWeek:  wh.DayOfWeek,
			StartTime:  wh.StartTime,
			EndTime:    wh.EndTime,
			ValidFrom:  wh.ValidFrom.Format("2006-01-02"),
			ValidUntil: vuStr,
		})
	}
	if resp == nil {
		resp = []dto.WorkingHoursResponse{}
	}
	return resp, nil
}

func (s *ScheduleService) UpdateWorkingHours(proID string, req []dto.CreateWorkingHoursRequest, ip, ua string) ([]dto.WorkingHoursResponse, error) {
	// Start transaction or simple query execution: first delete all existing hours
	if err := s.scheduleRepo.DeleteAllWorkingHours(proID); err != nil {
		return nil, err
	}

	var resp []dto.WorkingHoursResponse
	for _, r := range req {
		validFrom := time.Now()
		if r.ValidFrom != "" {
			parsed, err := time.Parse("2006-01-02", r.ValidFrom)
			if err == nil {
				validFrom = parsed
			}
		}

		var validUntil *time.Time
		if r.ValidUntil != "" {
			parsed, err := time.Parse("2006-01-02", r.ValidUntil)
			if err == nil {
				validUntil = &parsed
			}
		}

		wh := &models.WorkingHours{
			ProfessionalID: proID,
			LocationID:     r.LocationID,
			DayOfWeek:      r.DayOfWeek,
			StartTime:      r.StartTime,
			EndTime:        r.EndTime,
			ValidFrom:      validFrom,
			ValidUntil:     validUntil,
		}

		if err := s.scheduleRepo.CreateWorkingHours(wh); err != nil {
			return nil, err
		}

		var vuStr *string
		if wh.ValidUntil != nil {
			v := wh.ValidUntil.Format("2006-01-02")
			vuStr = &v
		}

		resp = append(resp, dto.WorkingHoursResponse{
			ID:         wh.ID,
			LocationID: wh.LocationID,
			DayOfWeek:  wh.DayOfWeek,
			StartTime:  wh.StartTime,
			EndTime:    wh.EndTime,
			ValidFrom:  wh.ValidFrom.Format("2006-01-02"),
			ValidUntil: vuStr,
		})
	}

	s.activitySvc.Log(&proID, "schedule.hours_updated", "working_hours", nil, nil, ip, ua)

	if resp == nil {
		resp = []dto.WorkingHoursResponse{}
	}
	return resp, nil
}
